# Generated by Django 4.0 on 2022-06-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
