# Generated by Django 4.0 on 2022-06-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posttag',
            options={'verbose_name': 'Post tag', 'verbose_name_plural': 'Post tags'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/posts'),
        ),
        migrations.AlterModelTable(
            name='posttag',
            table='post_tags',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tag',
        ),
    ]
