# Generated by Django 4.0 on 2022-06-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, through='post.PostTag', to='post.Tag'),
        ),
    ]
