# Generated by Django 4.0 on 2022-06-19 11:29

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_baseuser_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='baseuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='baseuser',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False, verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='username'),
        ),
    ]
