# Generated by Django 4.0 on 2022-06-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_baseuser_managers_baseuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='is_superuser',
            field=models.BooleanField(blank=True, default=False, verbose_name='superuser status'),
        ),
    ]
