name: CI/CD master branch

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]

    runs-on: ubuntu-latest

    # pending to solve the GitHub issue `The SECRET_KEY setting must not be empty`
    # steps:
    #   - uses: actions/checkout@v2
    #   - name: Set up Python ${{ matrix.python-version }}
    #     uses: actions/setup-python@v2
    #     with:
    #       python-version: ${{ matrix.python-version }}
    #   - name: Install Dependencies
    #     run: |
    #       python -m pip install --upgrade pip
    #       pip install -r requirements.txt
    #   - name: Run Tests
    #     run: |
    #       python manage.py test